export const SEARCH_LOCATE = 'SEARCH_LOCATE';
export const SEARCH_LOCATE_SUCCESS = 'SEARCH_LOCATE_SUCCESS';
export const SEARCH_LOCATE_FAILURE = 'SEARCH_LOCATE_FAILURE';

export const SEARCH_EMAILID = 'SEARCH_EMAILID';
export const SEARCH_EMAILID_SUCCESS = 'SEARCH_EMAILID_SUCCESS';
export const SEARCH_EMAILID_FAILURE = 'SEARCH_EMAILID_FAILURE';